name: sdl
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip
  - pip:
      - ninja
      - accelerate
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.49.0
      - blinker==1.9.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorlog==6.10.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.2.0
      - datasets
      - decorator==5.2.1
      - dill==0.4.0
      - einops==0.8.1
      - embreex==2.17.7.post7
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jaxtyping==0.3.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - lxml==6.0.2
      - manifold3d==3.2.1
      - mapbox-earcut==1.0.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - multidict==6.7.0
      - multiprocess
      - narwhals==2.10.2
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==2.2.6
      - numpy-quaternion==2024.0.12
      - omegaconf==2.3.0
      - open3d==0.19.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - peft
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.4.0
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pybind11==3.0.1
      - pycollada==0.9.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pytest==9.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rerun-sdk==0.26.2
      - retrying==1.4.2
      - rich==14.2.0
      - roma==1.5.4
      - rpds-py==0.28.0
      - rtree==1.4.1
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - setuptools-scm==9.2.2
      - shapely==2.1.2
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - svg-path==7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.22.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers
      - trimesh==4.9.0
      - trl==0.12.0
      - tzdata==2025.2
      - unsloth
      - unsloth-zoo
      - urllib3==2.5.0
      - vhacdx==0.0.9
      - wadler-lindig==0.1.7
      - warp-lang==1.10.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - yarl==1.22.0
      - yourdfpy==0.0.58
      - zipp==3.23.0
      - lark
prefix: /home/home/anaconda3/envs/sdl
