##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
robot: 'fairino5_v6_robot'
urdf_path: "robot/dcp_description/urdf/robot/fr5_ag95.urdf"
collision_spheres: 
  shoulder_link:
    - 'center': [-0.0, -0.004, 0.159]
      'radius': 0.08675
  upperarm_link:
    - 'center': [0.001, -0.0, 0.14]
      'radius': 0.08774
    - 'center': [-0.423, -0.003, 0.147]
      'radius': 0.08495
    - 'center': [-0.22, -0.0, 0.138]
      'radius': 0.05883
    - 'center': [-0.156, 0.0, 0.138]
      'radius': 0.05883
    - 'center': [-0.283, -0.0, 0.138]
      'radius': 0.05883
    - 'center': [-0.073, 0.002, 0.136]
      'radius': 0.07051
    - 'center': [-0.354, 0.0, 0.136]
      'radius': 0.06161
  forearm_link:
    - 'center': [-0.009, 0.002, 0.035]
      'radius': 0.07595
    - 'center': [-0.392, 0.0, 0.004]
      'radius': 0.06989
    - 'center': [-0.249, 0.0, 0.0]
      'radius': 0.05439
    - 'center': [-0.121, -0.0, -0.0]
      'radius': 0.05439
    - 'center': [-0.059, 0.001, 0.0]
      'radius': 0.05338
    - 'center': [-0.313, 0.001, -0.0]
      'radius': 0.05388
    - 'center': [-0.184, -0.0, 0.0]
      'radius': 0.05439
  wrist1_link:
    - 'center': [-0.0, 0.004, 0.101]
      'radius': 0.06448
  wrist2_link:
    - 'center': [-0.0, -0.005, 0.097]
      'radius': 0.06448
  wrist3_link:
    - 'center': [-0.004, -0.002, 0.115]
      'radius': 0.05788
    - 'center': [-0.005, -0.001, 0.085]
      'radius': 0.05694
    - 'center': [-0.001, -0.002, 0.186]
      'radius': 0.05788
  gripper_finger1_finger_tip_link:
    - 'center': [-0.001, 0.0, 0.022]
      'radius': 0.01072
    - 'center': [0.0, -0.003, 0.0]
      'radius': 0.01072
    - 'center': [0.021, 0.004, -0.004]
      'radius': 0.0102
    - 'center': [-0.002, -0.003, 0.024]
      'radius': 0.01072
    - 'center': [-0.0, 0.003, 0.0]
      'radius': 0.0102
    - 'center': [-0.003, 0.004, 0.027]
      'radius': 0.00967
    - 'center': [-0.004, 0.006, 0.017]
      'radius': 0.00862
    - 'center': [0.021, -0.005, -0.006]
      'radius': 0.00862
    - 'center': [-0.004, -0.0, 0.012]
      'radius': 0.0081
    - 'center': [-0.004, 0.006, 0.037]
      'radius': 0.0081
    - 'center': [0.011, 0.011, -0.004]
      'radius': 0.0081
    - 'center': [-0.004, -0.005, 0.037]
      'radius': 0.0081
    - 'center': [0.011, -0.011, -0.004]
      'radius': 0.0081
    - 'center': [-0.004, -0.007, 0.013]
      'radius': 0.0081
    - 'center': [-0.004, 0.006, 0.01]
      'radius': 0.0081
    - 'center': [-0.0, 0.011, -0.0]
      'radius': 0.0081
    - 'center': [0.0, -0.011, 0.0]
      'radius': 0.0081
    - 'center': [0.005, -0.003, -0.002]
      'radius': 0.0102
    - 'center': [-0.004, -0.0, 0.033]
      'radius': 0.0081
    - 'center': [-0.002, -0.002, 0.021]
      'radius': 0.01072
  gripper_finger2_finger_tip_link:
    - 'center': [-0.001, -0.001, 0.011]
      'radius': 0.01072
    - 'center': [0.0, -0.003, 0.0]
      'radius': 0.01072
    - 'center': [0.008, 0.002, -0.003]
      'radius': 0.0102
    - 'center': [-0.002, -0.003, 0.024]
      'radius': 0.01072
    - 'center': [-0.0, 0.003, 0.0]
      'radius': 0.0102
    - 'center': [-0.003, 0.004, 0.027]
      'radius': 0.00967
    - 'center': [-0.004, 0.006, 0.017]
      'radius': 0.00862
    - 'center': [0.012, -0.008, -0.003]
      'radius': 0.00862
    - 'center': [-0.004, -0.0, 0.012]
      'radius': 0.0081
    - 'center': [-0.004, 0.006, 0.037]
      'radius': 0.0081
    - 'center': [0.02, 0.004, -0.007]
      'radius': 0.0081
    - 'center': [-0.004, -0.005, 0.037]
      'radius': 0.0081
    - 'center': [0.02, -0.008, -0.008]
      'radius': 0.0081
    - 'center': [-0.004, -0.007, 0.013]
      'radius': 0.0081
    - 'center': [-0.004, 0.006, 0.01]
      'radius': 0.0081
    - 'center': [-0.0, 0.011, -0.0]
      'radius': 0.0081
    - 'center': [0.0, -0.011, 0.0]
      'radius': 0.0081
    - 'center': [0.005, -0.003, -0.002]
      'radius': 0.0102
    - 'center': [-0.004, -0.0, 0.033]
      'radius': 0.0081
    - 'center': [-0.002, 0.002, 0.018]
      'radius': 0.01072
  gripper_finger1_finger_link:
    - 'center': [0.006, -0.008, 0.024]
      'radius': 0.01409
    - 'center': [0.006, 0.003, 0.012]
      'radius': 0.01409
    - 'center': [0.012, 0.011, 0.025]
      'radius': 0.01347
    - 'center': [0.018, 0.011, 0.043]
      'radius': 0.01285
    - 'center': [0.009, -0.002, 0.017]
      'radius': 0.01285
    - 'center': [0.016, -0.01, 0.041]
      'radius': 0.01347
    - 'center': [0.006, -0.004, 0.011]
      'radius': 0.01409
  gripper_finger2_finger_link:
    - 'center': [0.006, -0.008, 0.011]
      'radius': 0.01409
    - 'center': [0.004, 0.008, 0.016]
      'radius': 0.01409
    - 'center': [0.012, 0.011, 0.034]
      'radius': 0.01347
    - 'center': [0.02, 0.007, 0.052]
      'radius': 0.01285
    - 'center': [0.017, -0.008, 0.041]
      'radius': 0.01285
    - 'center': [0.008, -0.01, 0.021]
      'radius': 0.01347
    - 'center': [0.006, -0.004, 0.011]
      'radius': 0.01409